import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[window]
padding = { x = 20, y = 20 }
opacity = 0.7

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[env]
TERM = "xterm-256color"
