[[manager.prepend_keymap]]
on = ["p"]
run = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = ["y"]
run = [
  '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''',
  "yank",
]

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"

[[manager.prepend_keymap]]
on   = "<Tab>"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"
